Project
emyrue/Module1Capstone pull request #1
Opened 2022-03-08 22:06 UTC by emyrue

Link to video: https://www.loom.com/share/90eedc1978cb45fab8504ecd6b2b1c5e
Made a website for an imaginary company that hosts concerts.

- Made a popup menu for the mobile version
- Made a fixed menu for the desktop version
- Made links to the about page in both versions
- Headline section, information section, featured artists section, partners section, etc. 
- Made links for past concerts on the about page

2022-03-08 22:41 UTC, MahmoudBakr23 requested changes
Hello @emyrue 😃, 

Great work and effort you put into this project so far.

## Highlights 🚀 

There are some excellent points that you have made perfectly. Keep up! 💪
- Linters are correct
- Great use of JavaScript
- Nicely done following the design and setting up the CSS media queries
- Great presentation video

However, there is always room for improvement.

> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️
_Please check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Please see my comments down below_

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-08 22:41 UTC, MahmoudBakr23 commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] Please fix the broken MIT link for a completely professional README file and repo 😄

2022-03-08 22:41 UTC, MahmoudBakr23 commented on README.md
> +
**OPTIONAL**
- It'd be very nice if you added a couple of images of the app under this nice description 😉

2022-03-08 22:41 UTC, MahmoudBakr23 commented on index.html
> +        </footer>
- [ ] Please make sure to include the footer in the mobile screen version of your app
_I know that the design frame doesn't show it. However, it doesn't make sense to remove the footer of the page in the mobile screen version right?_ 😕

2022-03-08 22:41 UTC, MahmoudBakr23 commented on myscript.js
> +}
- [ ] Please double-check on the menu functionality when the user is on the about page. Currently, the user cannot roll back from the about page to the home page using the menu icon on the mobile screen version! 🙏

2022-03-09 16:41 UTC, keroloussamy approved these changes
Hi @emyrue, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-09 18:16 UTC, merged